--> Create a table called EMPLOYEE table and allow NULL for all columns except EMPNO, ENAME, DOJ and JOB.
CREATE TABLE EMPLOYEE (
    EMPNO NUMERIC(6) NOT NULL,
    ENAME VARCHAR(10) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    DOJ DATE NOT NULL,
    JOB VARCHAR(30) NOT NULL,
    MGR NUMERIC(4),
    DEPTNO NUMERIC(3),
    SAL NUMERIC(7, 2),
    PRIMARY KEY (EMPNO)
);

