--> Select all employees from ‘EE’, ‘IS’ and ‘CSE’ department using UNION operator.
SELECT E.* FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'EE'
UNION
SELECT E.* FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'IS'
UNION
SELECT E.* FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'CSE';
